### ISSUE TITLE
Some tweens randomly will not be scheduled

### ISSUE THREAD

**Issue by rhyok** [dentedpixel/LeanTween#80] opened 2016-05-23 21:20 UTC
Hey again dented,

So... we have instances where scheduled TweenAlpha calls will not schedule tweens properly. The reproduction case is relatively complicated in our app and I'm not sure what is happening that makes this issue happen, so I'm sorry this report isn't very detailed heh. 

The basic overview is that it seems like, after a certain sequence of tweens is played in our certain other tweens stop behaving properly. Specifically, a call to LeanTween.alphaText just does not do anything at randoms after playing a lot of tweens in our game. There are no exceptions, and no errors to accompany it, so I'm not sure why it's failing.

I've emailed you a video which should make this issue clearer. I'd prefer not to make this public, as it shows a little bit of the innards of a project we've have out on the App Store, but please feel free to contact me via email if you need more details.

**Comment by dentedpixel** [comment] 2016-05-24 10:44
I can't see anything that stands out as wrong from the video. When you leave the play menu to go to that other menu, are you loading a new scene? Or is that just transitioning out the pieces within the same scene? Can you print out the other variables inputted to LeanTween, like the delay and speed. Maybe somehow it just got setup with a really long delay?

It would be great to get some type of reproduction steps, if you find a way to simplify the steps with code that could be shared would be great (I know you are probably reluctant to share the whole project).

**Comment by madangosain** [comment] 2016-07-24 21:47
Ditto, I am seeing the same behavior from last few months. Problem arise with schedule tweens which are never invoked in certain situations. I suspect problem with:
Leantween.delayedCall(
and .setDelay(

I've noticed this issue in multiple apps. Unfortunately I cannot provide exact repro steps as it is random, but it could be related to conflicting tweens.

**Comment by madangosain** [comment] 2016-07-24 22:20
```
1) Correct TWEEN when played
tweens[4]: True : gameObject:**FacebookHelpTextBg** (UnityEngine.GameObject) toggle:True passed:0 time:0.3 delay:0.8 direction:1 from:(0.0, 1.0, 1.0) to:(1.0, 1.0, 1.0) type:SCALE ease:linear useEstimatedTime:True id:4390916 hasInitiliazed:False

2) Normally ~LeanTween becomes the [0] tween 
tweens[0]: True : gameObject:**~LeanTween** (UnityEngine.GameObject) toggle:True passed:0.1023131 time:0.5 delay:0 direction:1 from:(100.0, 0.0, 0.0) to:(0.0, 0.0, 0.0) type:CALLBACK ease:linear useEstimatedTime:False id:7667712 hasInitiliazed:True

3) PROBLEM TWEEN, this supposed to be scale tween as shown in first sceneio
tweens[0]: True : gameObject:**FacebookHelpText** (UnityEngine.GameObject) toggle:True passed:0.635797 time:2 delay:0 direction:1 from:(0.0, 0.0, 0.0) to:(20.0, 0.0, 0.0) type:CALLBACK ease:linear useEstimatedTime:False id:8519680 hasInitiliazed:True
```
Problem only happen with tweens[0] and it is never started..

**Comment by madangosain** [comment] 2016-07-24 22:49
My developer have sent you an email with detailed LeanTween logs and problem repro details

**Comment by dentedpixel** [comment] 2016-07-27 11:14
Ok thanks! I am looking into it, in the meantime you might want to try the work around I suggested: using LeanTween.reset(); at the start of each scene.

**Comment by dentedpixel** [comment] 2016-07-28 11:23
Hi, I have made a scene that attempts to reproduce this bug, but I have not had any luck doing so. Could you, or your developer look at LeanTween/Testing/TestingSceneSwitching scene and add anything you can to help reproduce the bug as you have seen it?

Thanks!

**Comment by madangosain** [comment] 2016-07-28 11:43
Did you try it in Unity 5.3.6? Thanks

**Comment by madangosain** [comment] 2016-07-28 12:31
I did created a new project and tried, but could not reproduce the issue with latest LeanTween plugin from Asset Store. I've updated my project with 
1) latest plugin from unity asset store
2) Removed all reference to LeanTween.cancel(gameobject) and started cancelling by TweenId instead
Now, I am not able to reproduce this in my project.  I believe plugin update may have fixed the issue but I'll still closely monitor it. Once again thank you for looking into this. 

On a separate note, is there any reason to put LeanTween files under root Assets/Plugin folder instead of having subfolder "LeanTween"? Normally project have several plugin and it clutters the root. 

Thank you for super awesome plugin and looking into this.

**Comment by dentedpixel** [comment] 2016-07-28 12:39
Oh great! I hope it is resolved in the latest, but let me know if you see something again.

Regarding the putting LeanTween in it's own subfolder, that has just been implemented in the latest github you can see, but the Asset Store doesn't have this cleanup yet. I agree this should be much cleaner and is long overdue.

Not a problem :), glad you are liking LeanTween.

**Closed** 2016-07-28 12:39 UTC
